"""add session lineage to refresh tokens

Revision ID: 2dea576639e9
Revises: a2f6c9e1b8d4
Create Date: 2026-09-13 17:33:22.821453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dea576639e9'
down_revision: Union[str, None] = 'a2f6c9e1b8d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Added nullable first and backfilled, rather than NOT NULL straight away
    # (autogenerate's default), so this doesn't fail against any existing
    # rows: each pre-existing token becomes its own session origin (id as
    # session_id, created_at as session_started_at) since no rotation
    # lineage was tracked before this migration.
    op.add_column('refresh_tokens', sa.Column('session_id', sa.UUID(), nullable=True))
    op.add_column('refresh_tokens', sa.Column('session_started_at', sa.DateTime(timezone=True), nullable=True))
    op.execute('UPDATE refresh_tokens SET session_id = id, session_started_at = created_at WHERE session_id IS NULL')
    op.alter_column('refresh_tokens', 'session_id', nullable=False)
    op.alter_column('refresh_tokens', 'session_started_at', nullable=False)
    op.create_index(op.f('ix_refresh_tokens_session_id'), 'refresh_tokens', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_session_id'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'session_started_at')
    op.drop_column('refresh_tokens', 'session_id')
    # ### end Alembic commands ###
